Fix death issues
mrrhetorical/COM-Warfare pull request #20
Opened 2021-02-17 17:04 UTC by Insprill

Fixes issues when a player dies due to something other than another player

2021-02-17 23:03 UTC, mrrhetorical requested changes
In `GameInstance#moveEvent(PlayerMoveEvent)`, it will prevent movement from anyone in spectator mode instead of just those in that GameInstance. This needs to only prevent movement from players in spectator mode in that match.

2021-02-18 09:17 UTC, Insprill commented
Damn it, used that to test and never changed it haha. Ill fix it in a day or two

2021-04-05 00:37 UTC, Insprill commented
bump

2021-04-05 01:24 UTC, mrrhetorical approved these changes

2021-04-05 01:24 UTC, merged